kind: Deployment
apiVersion: apps/v1
metadata:
  name: xmen-meli
  labels:
    app: xmen-meli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xmen-meli
  template:
    metadata:
      labels:
        app: xmen-meli
    spec:
      containers:
        - name: xmen-meli
          image: matiasresca/xmen-meli:latest
          imagePullPolicy: Always
          ports:
            - name: web-backend
              containerPort: 8080
          env:
            - name: MONGO_HOST
              value: "mongo"
---
apiVersion: v1
kind: Service
metadata:
  name: xmen-meli
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web-backend
      port: 80
      targetPort: 8080
  selector:
    app: xmen-meli